name: Auto deploy snapshot on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Linux
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Release tag
        run: |
          git describe --tags --always --first-parent
          git tag

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish application
        run: |
          echo VERSION_NAME=1.0.0-SNAPSHOT > ./local.properties
          ./gradlew :premex-lint-checks:publishToSonatype --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2